GrpcPort: 8080
HttpPort: 8090
WSPort: 8091
APIPort: 8070
MetricPort: 8060
AgentOpsPort: 8050

CpName: demo
LogType: log-query-service

LogLevel: DEBUG
LogOut: console
LogFile: ./logs/demo.log
LogMaxDays: 30

IsRemoteBizLog: true
AsyncChainSize: 20000
DefaultAppID: CB2W28VA
DefaultProductLine: com
DefaultBizID: com
KafkaClientExt:
  bootstrap.servers: "172.31.114.161:9092"
  acks: "all"